In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
dataset= pd.read_csv('A:\Academics\ASMAT\IIT Bhilai\Machine Learning\Social_Network_Ads.csv')
dataset.head(n=1)

Age  EstimatedSalary  Purchased
0   19            19000          0

In [3]:
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [4]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

In [5]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train) # simply feature scaling whole data set. No need to select Any specific Column
X_test = sc.transform(X_test)

In [6]:
#X_train


In [7]:
#X_test

In [8]:
# Training the dataset

In [9]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0)

In [10]:
classifier.fit(X_train, y_train) 

LogisticRegression(random_state=0)

In [11]:
# Predicting a new result

In [12]:
classifier.predict(sc.transform([[55, 87000]])) # Transform is necessary

array([1], dtype=int64)

In [13]:
y_pred = classifier.predict(X_test)
print(y_pred)
#print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 1 0 0 1 0 1 0 1 0 0 0 0 0 0 1 0 0 0 0
 0 0 1 0 0 0 0 1 0 0 1 0 1 1 0 0 0 1 0 0 0 0 0 0 1 0 0 0 1 0 0 0 0 1 0 0 0
 0 0 1 0 1 1 1 1 0 0 1 1 0 1 0 0 0 1 0 0 0 0 0 0 1 1]


In [14]:
# Confusion matrix (Simply what is the prediction or, Percentage of correctness)

In [15]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)
# [[65 3]
 #  [8 24]] means 65 correct who didn't purchased car and predicted that they didn't purchased
    # 24 means that correct prediction that purchased car and really purchased car
    # 3 means incorrect prediction bought car in reality but showing not purchased
    # 8 means incorrect prediction , didn't bought car but showing bought the car
    #0.89 is the percentage of accuracy


[[65  3]
 [ 8 24]]


0.89

In [ ]:
# Visualisation for Logistic Regression is very complex indeed. So, not needed. although code is provided in Course.